# 开发环境
# 服务启动使用的端口
server:
  port: 8888
  max-http-header-size: 10MB
  tomcat:
    max-http-post-size: 10MB

# 数据库配置
spring:
  datasource:
    druid:
      url: jdbc:mysql://rm-2zeq7v30r2bmcul903o.mysql.rds.aliyuncs.com:3306/photo_db?zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true
      username: root
      password: Sol2019password
      driverClassName: com.mysql.jdbc.Driver
      # connection-init-sqls: set names utf8mb4
      #最大活跃数
      maxActive: 20
      #初始化数量
      initialSize: 1
      #最大连接等待超时时间
      maxWait: 60000
      #打开PSCache，并且指定每个连接PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
      #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
      filters: stat, log4j2
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

mybatis:
  mapper-locations: classpath:com/sol/dao/mapper/*.xml
# 配置日志
logging:
  config: classpath:log4j2-spring.xml
  level:
    com.jbtx.dao: debug

data:
  test:
    envName: dev
    envconfig: 127.0.0.1:8081








